In [13]:
import torch
import numpy as np

In [14]:
# 2. Set the random seed for NumPy and PyTorch both to "42"
torch.manual_seed(42)
np.random.seed(42)

In [15]:
# 3. Create a NumPy array called "arr" that contains 6 random integers between 0 and 5
arr = np.random.randint(0, 5, size=6)

print(arr)

[3 4 2 4 4 1]


In [16]:
# 4. Create a tensor "x" from the array above
x = torch.tensor(arr)

print(x)

tensor([3, 4, 2, 4, 4, 1])


In [17]:
# 5. Change the dtype of x from 'int32' to 'int64'
x = x.to(torch.int64)

print(x)

tensor([3, 4, 2, 4, 4, 1])


In [18]:
# 6. Reshape x into a 3x2 tenso
x_reshaped = x.reshape(3, 2)
print(x_reshaped)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [19]:
# 7. Return the right-hand column of tensor x
right_column = x_reshaped[:, 1:]
print(right_column)

tensor([[4],
        [4],
        [1]])


In [20]:
# 8. Without changing x, return a tensor of square values of x
x_squared = x_reshaped ** 2
print(x_squared)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [21]:
# 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
y = torch.randint(0, 5, (2, 3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [22]:
# 10. Find the matrix product of x and y
matrix_product = torch.matmul(x_reshaped, y)
print(matrix_product)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
